POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer 

{
    "title": "Testing create blog with auth",
    "author": "John D",
    "url": "https://medium.com",
    "likes": 2
}
