POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "Reflections of a woman entering Tech",
    "author": "Madhushree B",
    "url": "https://medium.com/@madhushree.b/reflections-of-a-woman-entering-tech-af1abf475eec",
    "likes": 10
}
