POST http://localhost:3001/api/notes/
Content-Type: application/json
Authorization: Bearer 

{
    "content": "Test new note creation",
    "important": false
}

### 
GET http://localhost:3001/api/notes/
