POST http://localhost:3001/api/notes/
Content-Type: application/json
Authorization: Bearer 

{
    "content": "Single page app use token based auth",
    "important": false
}

### 
GET http://localhost:3001/api/notes/
