POST http://localhost:3001/api/notes/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY1ZDc2YWY5Y2MwMjRmMGQ4ZWEzMGUyMCIsImlhdCI6MTcwODY5MzU2MX0.HPPEkv8iAm2KfOqNgZd7Yf6jpufn6OXCknDXRoEsmoE

{
    "content": "Single page app use token based auth",
    "important": false
}

### 
GET http://localhost:3001/api/notes/
